name: E2e test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      access-token:
        required: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: print github owner and repo
        run: |
          echo "Github onwer and repo: ${{ github.repository}}"
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: rizwanm-devops/sample-app-1
          ref: main
          token: ${{ secrets.TEST_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run E2e tests
        run: npm run test:e2e
